### ISSUE TITLE
a problem when running "./android-patchsets/hikey-optee-4.9 "

### ISSUE THREAD

**Issue by wxlqaz** [linaro-swg/optee_android_manifest#19]
Hi,
I follow the step in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master but when I was in step 3.4 (3.4. Apply the required patches (please respect order!) and run "./android-patchsets/hikey-optee-4.9 " it shows that:

=== Applying 17712/1 ===
From git://android-review.linaro.org/kernel/hikey-linaro
 * branch            refs/changes/12/17712/1 -> FETCH_HEAD
[detached HEAD 2742d3b] staging/ion: add Allwinner ION "secure" heap **not for mainline**
 Author: Etienne Carriere <etienne.carriere@linaro.org>
 Date: Thu Mar 23 14:02:08 2017 +0100
 2 files changed, 180 insertions(+)
 create mode 100644 drivers/staging/android/ion/ion_secure_heap.c
=== Applying 17713/1 ===
From git://android-review.linaro.org/kernel/hikey-linaro
 * branch            refs/changes/13/17713/1 -> FETCH_HEAD
error: could not apply f1fcf9f... ion: "unmapped" heap for secure data path **not for mainline**
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
17713/1 failed to apply, please fix
HEAD is now at 2742d3b staging/ion: add Allwinner ION "secure" heap **not for mainline**

Could you please tell me how to fix it? 
Thank you so much!

**Comment by duduscript** [comment]
I have the same problem as yours

**Comment by vchong** [comment]
The kernel was updated with changes that conflicted with the patches. Will fix and update.

**Comment by wxlqaz** [comment]
Thank you very much!

**Comment by wxlqaz** [comment]
Hi，
I have tried it again and I'm sorry to find that this problem still exists.
Bests

**Comment by vchong** [comment]
It's not fixed yet. Will post an update here when it's done. Please wait. Thanks for your patience.

**Comment by wxlqaz** [comment]
Thanks~

**Comment by vchong** [comment]
@wxlqaz @duduscript The build error should be fixed now, but as a result of some new patches in the kernel that conflicts with op-tee ion patches, sdp has been disabled for now. Hopefully we can re-enable it soon in the future. Again, sorry for the delay and thanks for your patience!

**Comment by wxlqaz** [comment]
Hi，
I have tried the new version , the patches work fine, but I'm sorry to find that the problems in #18 still exists.  In fact, I'm confused that whether I need to download other files about OP-TEE before the step 3 in  https://github.com/linaro-swg/optee_android_manifest ? 
Thank you!

**Comment by wxlqaz** [comment]
Hi，
By the way, Is it a normal phenomenon that when I make files( make TARGET_BUILD_KERNEL=true TARGET_BUILD_UEFI=true CFG_SECURE_DATA_PATH=n ) there exists some "warnings"?
And is it essential I must use the "android-7.1.2_r33" instead of the previous version "android-7.1.2_r11" ?
Thank you very much.

**Comment by vchong** [comment]
> I'm confused that whether I need to download other files about OP-TEE before the step 3

What files are you referring to specifically?

> Is it a normal phenomenon that when I make files there exists some "warnings"?

Yes

> Is it essential I must use the "android-7.1.2_r33" instead of the previous version "android-7.1.2_r11"?

No. Afaik r11 should still be ok atm. No guarantee though as time passes.

> The problems in #18 still exists.

Try pasting your build log on a pastebin somewhere.
@duduscript Do you have the same problem?

**Comment by wxlqaz** [comment]
Hi,
Thanks for your reply,
About the first one. I have installed the required applications as step 2 said, but this sentence:" In addition, you will need the pre-requisites necessary to build optee-os."  make  me confused. Should I build the optee-os before step 3. How do I build it?
Thank you very much!

**Comment by vchong** [comment]
No, you don't need to build optee_os before step 3. Step 2 is just to make sure you have the pre-requisites (i.e. SW packages) required to complete the build.

1. Can you build regular android (i.e. without op-tee) for hikey following the instructions in https://source.android.com/source/initializing, and run the images without problems?

2. After you verify 1, then do:
```
$ sudo apt-get install android-tools-adb android-tools-fastboot android-tools-fsutils autoconf \
	automake bc bison build-essential cscope curl device-tree-compiler dosfstools flex \
	ftp-upload gdisk iasl install libattr1-dev libc6:i386 libcap-dev libfdt-dev \
	libftdi-dev libglib2.0-dev libhidapi-dev libncurses5-dev \
	libpixman-1-dev libssl-dev libstdc++6:i386 libtool libz1:i386 make \
	mtools netcat python-crypto python-serial python-wand realpath unzip uuid-dev \
	xdg-utils xterm xz-utils zlib1g-dev
```
Most of these should already be installed on your system, but just list everything out here again to be safe. This will ensure you have all the SW packages required to build optee_os properly. Note that this is for ubuntu systems, which I assume is the one you're using?

3. Proceed with the rest of the instructions to build android with op-tee.

**Comment by wxlqaz** [comment]
Thanks,  I may ignore some of this. I will try it. Thank you!

**Comment by wxlqaz** [comment]
Hi,
I 'm sorry, but I have tried it again but when I run "xtest" , it still shows as follows:

```bash
root@hikey:/ # xtest
Run test suite with level=0

TEE test application started with device [(null)]
Failed to open TEE context: 0xffff0008
255|root@hikey:/ #
```

And things are the same when I run the "tee_helloworld":

```bash
255|root@hikey:/ # tee_helloworld
tee_helloworld: TEEC_InitializeContext failed with code 0xffff0008
```

The code "0xffff0008" means "items-not-founded" in. It seems like the optee driver is missing in my hikey board. So May it exists some possible methods to fix it?

Thanks for your patience and help!

**Comment by jockebech** [comment]
Is tee-supplicant running (`ps -a | grep tee-supplicant`)? Has the OP-TEE driver been probed (`dmesg | grep optee` .. usually gives two lines where the last line says `optee: initialized driver`)?

**Comment by wxlqaz** [comment]
Hi,
when I run  (ps -a | grep tee-supplicant), it shows nothing
when I run (dmesg | grep optee..) it shows 

```bash
1|root@hikey:/ # dmesg | grep optee..                                          
[    4.815090] optee: probing for conduit method from DT.
[    4.820341] optee: api uid mismatch
```

Thanks.

**Comment by jockebech** [comment]
The TEE driver seems OK, since it is trying to probe, but the output you pasted tells us that it fails to load the TEE (OP-TEE) and due to that tee-supplicant cannot register and ... therefore xtest doesn't run. So, the first thing I would investigate is if OP-TEE has been flashed and what version. If you have the UART log from secure side, then you should be able to see a debug print when booting saying something like this:
`INFO:    TEE-CORE: OP-TEE version: 2.5.0-35-g9aea3dc8 #1 Wed Aug 16 07:22:10 UTC 2017 arm`
and a bit further down you should see
`INFO:    TEE-CORE: Initialized`

If you don't see that, then most likely OP-TEE hasn't been flashed. The binary for OP-TEE is included in fip.bin, so that is the one that you need to fiddle with when updating the TEE itself. Contrary, if you indeed to see that, please pay attention to the version. From time to time there are dependencies between the various components in OP-TEE. Best way is to either run a stable release (2.5.0 is the latest) or run latest on all gits. Could you please give this a try? That might lead somewhere.

**Comment by wxlqaz** [comment]
Hi，
I use a logcat to print UART log, the only thing about TEE is that:

```log
01-01 00:00:12.063 1886-1886/? W/tee-supplicant: type=1400 audit(0.0:4): avc: denied { add_name } for name="teec.log" scontext=u:r:tee:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0
```

thanks

**Comment by wxlqaz** [comment]
Hi,
when I using "ls system/bin" the "tee" "tee_helloworld" and "tee_supplicant" is exists in my hikey board

**Comment by vchong** [comment]
As requested earlier, please paste your build log, and also flash log, somewhere so we can check for errors.

If no errors then we'll have to find some time to test a fresh build and run.

**Comment by vchong** [comment]
The build log will be huge so suggest you use termbin.com or something similar.

**Comment by vchong** [comment]
@wxlqaz As a test, can you try flashing https://builds.96boards.org/snapshots/reference-platform/components/uefi/latest/release/hikey/fip.bin and let us know if it works? Thanks.

**Comment by wxlqaz** [comment]
Hi,
I have used the fip.bin file in  https://builds.96boards.org/snapshots/reference-platform/components/uefi/latest/release/hikey/fip.bin and the TEE WORKS FINE!
when I run the "tee_helloworld", it shows: 
17|root@hikey:/ # tee_helloworld                                               
Invoking TA to increment 42
TA incremented value to 43

The result of running "xtest" is a little long, I can show you the final result:
23155 subtests of which 26 failed
78 test cases of which 18 failed
0 test case was skipped
TEE test application done!
This is the whole log when running xtest, the regression 4003, 6003,6009,6010 and  9xxx are failed
[log.txt](https://github.com/linaro-swg/optee_android_manifest/files/1233125/log.txt)

Thanks for your continuously help!

**Comment by wxlqaz** [comment]
Hi,
the log may be composed terrible, this is the pdf file of the log 
[log.pdf](https://github.com/linaro-swg/optee_android_manifest/files/1233871/log.pdf)

**Comment by vchong** [comment]
@wxlqaz Confirmed with one of our android engineers that there was an issue that should be fixed now. Sorry for your trouble, and thanks for the report and testing. I've updated the instructions, so please delete your build dir's `out` folder, do a `repo sync`, follow the instructions again from `3.4` and let us know how it goes. Thanks!

**Comment by wxlqaz** [comment]
Hi,
I have tried it and when I run "xtest", it shows no failed:

23902 subtests of which 0 failed
78 test cases of which 0 failed
0 test case was skipped
TEE test application done!

Thank you very much!
